### ISSUE TITLE
Port Damage Tint to Forge

### ISSUE THREAD

**Issue by MrChurch2005** [DeadlyMC/damage-tint#1]
This mod is exactly what I was looking for! Unfortunately, the mods I prefer to play with are for forge only. I could use enhanced visuals, but I think that mod is a little bit over the top. Porting this mod to forge would be a game changer!

**Comment by DeadlyMC** [comment]
Just uploaded a forge port on curseforge! Get the jar from here:
https://www.curseforge.com/minecraft/mc-mods/damage-tint/files/3173444

You can check out the source code here: https://github.com/DeadlyMC/damage-tint/tree/forge/1.16.x

**Comment by DeadlyMC** [comment]
Please download the jar and confirm if it works for you so i could close this github issue :)

**Comment by MrChurch2005** [comment]
It works perfectly! Thank you!
