### ISSUE TITLE
Max Health calculations to make Tint not broke with some Health-changing mods

### ISSUE THREAD

**Issue by ZettaSword** [DeadlyMC/damage-tint#2]
If you'll calc the amplitude to tint using Player Max Health and checking is it percentage(configurable one) is equals or lower then current one or smth like this..  That way mods which reduce/add to player health will be not broken at all

**Comment by DeadlyMC** [comment]
Which mods have u tested with btw?

**Comment by Drebledore** [comment]
Try Scaling Health or PlayerEx both have changing HP feature (Scaling health does its own and PlayerEx vanilla hp attribute)

**Comment by DeadlyMC** [comment]
Try out v1.1.0 forge, this brings `/tint dynamic` which always uses the max health value when calculating threshold. Also the threshold is not restricted to numbers between 0 and 20 anymore.
https://www.curseforge.com/minecraft/mc-mods/damage-tint/files/3380962
Reopen this issue if you have issues with the same mod or create another issue.
