### ISSUE TITLE
[FORGE] Compatibility issue with Hardcore Revival

### ISSUE THREAD

**Issue by alpharou** [DeadlyMC/damage-tint#3]
versions:
forge 36.0.43
HardcoreRevival_1.16.3-5.2.0
damage-tint-forge-1.16.5-1.0.1

I'll post an issue in both repositories:

The screen turns weird and black instead of showing your surroundings:
![image](https://user-images.githubusercontent.com/8113318/110646922-ac9e8400-81b7-11eb-9fa8-5d1df3f6241a.png)

**Comment by DeadlyMC** [comment]
Looks like the mod author got it fixed, thanks for reporting though https://github.com/blay09/HardcoreRevival/commit/853b4c67c7bde3dacbb4b97c5a8bce2934a4078d
