### ISSUE TITLE
Mod is incompatible with 1.17.

### ISSUE THREAD

**Issue by Kichura** [DeadlyMC/damage-tint#5]
When attempting to use this mod in 1.17, the game just gives up since the java code is entirely different.

**Comment by DeadlyMC** [comment]
Working on it

**Comment by DeadlyMC** [comment]
Fabric version just went live : https://www.curseforge.com/minecraft/mc-mods/damage-tint/files/3362256
Forge for 1.17 is not out yet, im gonna leave this issue open until the forge version goes live

**Comment by DeadlyMC** [comment]
Forge for 1.17 is out too, yea took quite long...
https://www.curseforge.com/minecraft/mc-mods/damage-tint/files/3482224
